### ISSUE TITLE
运行Deploy.sh后，执行hooker命令，进程不会出现提示frida-ps 未找到命令

### ISSUE THREAD

**Issue by xpl520** [CreditTone/hooker#20]
Redmi Note 9 运行Deploy.sh后，执行hooker命令，进程不会出现提示frida-ps 未找到命令

**Comment by CreditTone** [comment]
是不是没安装frida-tools? 有报错吗

**Comment by xpl520** [comment]
![image](https://user-images.githubusercontent.com/33258979/114122458-dec01480-9922-11eb-95a9-783d436d5469.png)
![image](https://user-images.githubusercontent.com/33258979/114122487-ebdd0380-9922-11eb-835f-7225de8935d0.png)

**Comment by xpl520** [comment]
> 是不是没安装frida-tools？有报错吗

上面这个是我运行截图呢

**Comment by CreditTone** [comment]
frida-ps  -U看看原生命令是否成功

**Comment by CreditTone** [comment]
报错的是https://github.com/CreditTone/hooker/blob/master/hooker中的这一行
frida-ps $HOOKER_DRIVER -ai | grep -v '@' | grep -v '    -  '
就是一个原生frida-ps命令
本人怀疑是环境变量有问题

**Comment by xpl520** [comment]
> 报错的是[https://github.com/CreditTone/hooker/blob/master/hooker中的这一行](https://github.com/CreditTone/hooker/blob/master/hooker%E4%B8%AD%E7%9A%84%E8%BF%99%E4%B8%80%E8%A1%8C)
> frida-ps $HOOKER_DRIVER -ai | grep -v '@' | grep -v ' - '
> 就是一个原生frida-ps命令
> 本人怀疑是环境变量有问题

![image](https://user-images.githubusercontent.com/33258979/114125617-6e68c180-9929-11eb-8f5d-881a9865d302.png)

**Comment by xpl520** [comment]
> 报错的是[https://github.com/CreditTone/hooker/blob/master/hooker中的这一行](https://github.com/CreditTone/hooker/blob/master/hooker%E4%B8%AD%E7%9A%84%E8%BF%99%E4%B8%80%E8%A1%8C)
> frida-ps $HOOKER_DRIVER -ai | grep -v '@' | grep -v ' - '
> 就是一个原生frida-ps命令
> 本人怀疑是环境变量有问题

行呢，我先看看环境变量，多谢老哥

**Comment by CreditTone** [comment]
好的
