### ISSUE TITLE
./hooking url.js 

### ISSUE THREAD

**Issue by rookiexjl** [CreditTone/hooker#21]
可以看  header 或者data cookies信息不

**Comment by CreditTone** [comment]
url.js的思想是通过hook一些系统的类比如android.net.Uri、java.net.URL以及com.android.okhttp.Request$Builder对象来帮助你定位app代码逻辑，进一步的信息需要你自己去看apk源码来hook应用自定义的类。同学，你思想就错了。没有通用的脚本！因为每个app在发版的时候都会混淆代码，通过hook脚本不可能对每个应用进行通用。比如com.android.okhttp.Request这个类在a应用叫x.za.d，在b应用叫q.x.ad。你让我怎么写脚本呢？所以还是好好了解技术原理吧，工具只是工具。看你怎么用，如果你原理不懂好工具在你面前你可能不能发挥它全部的价值。

回到你这个问题上，怎么获取 header或者data cookies?
1、我会尝试去用charles之类抓包工具，直接抓包，简单快捷。
2、如果不能抓包，我会去看看./hooking url.js带出来的堆栈信息去jadx看apk的源代码。看看header的封装类然后hook之。而hooker的核心功能就是生成hook脚本让你为写脚本而浪费时间了。

**Comment by CreditTone** [comment]
url.js的思想是通过hook一些系统的类比如android.net.Uri、java.net.URL以及com.android.okhttp.Request$Builder对象来帮助你定位app代码逻辑，进一步的信息需要你自己去看apk源码来hook应用自定义的类。同学，你思想就错了。没有通用的脚本！因为每个app在发版的时候都会混淆代码，通过hook脚本不可能对每个应用进行通用。比如com.android.okhttp.Request这个类在a应用叫x.za.d，在b应用叫q.x.ad。你让我怎么写脚本呢？所以还是好好了解技术原理吧，工具只是工具。看你怎么用，如果你原理不懂好工具在你面前你可能不能发挥它全部的价值。

回到你这个问题上，怎么获取 header或者data cookies?
1、我会尝试去用charles之类抓包工具，直接抓包，简单快捷。
2、如果不能抓包，我会去看看./hooking url.js带出来的堆栈信息去jadx看apk的源代码。看看header的封装类然后hook之。而hooker的核心功能就是生成hook脚本让你不用为写脚本而浪费时间了。

**Comment by rookiexjl** [comment]
感谢老铁的耐心解答 抓包没找到有些隐藏的 我好好看下源码分析下
