### ISSUE TITLE
运行sh /sdcard/mobile-deploy/deploy.sh后，./hooker启动输入包名后手机重启了

### ISSUE THREAD

**Issue by cat13954** [CreditTone/hooker#35]
Mac os 10.15.6
手机nexus 5，Android 6.0.1，已经root，已安装xposed。
Python 3.7.x

按照GitHub上面的流程，clone了项目，push了文件夹，和sh启动了deploy脚本。
./hooker启动后，输入了其中一个包名，比如wx的。然后手机重启了。
重试了几次，都重启了手机。

**Comment by cat13954** [comment]
因为之前没使用过frida，我是需要先安装一次frida？还是说不需要了？

**Comment by CreditTone** [comment]
先测试其他app看是否重启，先排除是不是微信问题

**Comment by cat13954** [comment]
> 先测试其他app看是否重启，先排除是不是微信问题

我自己写的APP也会，就一个简单的hello world，我尝试了其他APP，同样出现过几秒就重启手机情况。

**Comment by nmweizi** [comment]
卸载xposed试试

**Comment by cat13954** [comment]
> 卸载xposed试试

这个手机的环境暂时不能动，我换了一台红米8a就可以了，非常感谢这个框架
