### ISSUE TITLE
输入包名后提示错误了

### ISSUE THREAD

**Issue by ff-frida** [CreditTone/hooker#36]
![微信截图_20210610182712](https://user-images.githubusercontent.com/18607031/121509881-a8357180-ca19-11eb-83ba-9f9d41d80a64.png)

环境：Ubuntu 1804
Android 9，小米8，已经安装edxposed，脸谱，已经root

>前面已经启动了hook，当输入某个包名的时候就这样提示了，这个是什么情况呢，大佬。如果有时间会告知下，麻烦了

**Comment by CreditTone** [comment]
你要调试这个app，你要先把它启动起来。

**Comment by ff-frida** [comment]
> 你要调试这个app，你要先把它启动起来。

感谢，已经🆗了，正在尝试文档中的功能
