### ISSUE TITLE
远程向夜神模拟器部署的时候无法启动frida-server，./hooker 无法看到应用

### ISSUE THREAD

**Issue by B16011122** [CreditTone/hooker#39]
夜神模拟器最新版，安卓7.1.2
win电脑安装夜神模拟器，vm虚拟机安装Ubuntu 18
tcpforward已开启

**Comment by CreditTone** [comment]
日志贴一下

**Comment by CreditTone** [comment]
再试下

**Comment by B16011122** [comment]
root@ubuntu://download/hooker# ./hooker 
Failed to enumerate applications: unable to connect to remote frida-server
Enter the need to attach package.
:

**Comment by B16011122** [comment]
执行deploy.sh会弹出adb，执行deploy2.sh不会弹出，请问有什么命令能在夜神模拟器里面确认是否启动了frida-server

**Comment by CreditTone** [comment]
建议用真机

**Comment by cykac04** [comment]
> 建议用真机

原因夜神是x86版本需要frida-server x86
但现在编译的是x86_64不能运行
能不能提供一个新的版本

**Comment by sang8052** [comment]
同样遇到了这个问题
我非常反对楼上回复的建议用真机的弱智回复，我要是能够用真机我要需要用模拟器？而且真机有时可能会造成不可逆的损失，你给我赔偿吗？
费劲千辛万苦，终于在[https://onejane.github.io/2021/02/12/基于内存定位分析/](https://onejane.github.io/2021/02/12/基于内存定位分析/)这篇文章中找到了 hluda-server 的项目地址 ，https://github.com/hluwa/strongR-frida-android/ ， 对应适配楼主的 x86_64 的server 文件地址 https://github.com/hluwa/strongR-frida-android/releases/download/14.2.13/hluda-server-14.2.13-android-x86_64

**Comment by oooodogecoin** [comment]
> 同样遇到了这个问题
> 
> 我非常反对楼上回复的建议用真机的弱智回复，我要是能够用真机我要需要用模拟器？而且真机有时可能会造成不可逆的损失，你给我赔偿吗？
> 
> 费劲千辛万苦，终于在[https://onejane.github.io/2021/02/12/基于内存定位分析/](https://onejane.github.io/2021/02/12/基于内存定位分析/)这篇文章中找到了 hluda-server 的项目地址 ，https://github.com/hluwa/strongR-frida-android/ ， 对应适配楼主的 x86_64 的server 文件地址 https://github.com/hluwa/strongR-frida-android/releases/download/14.2.13/hluda-server-14.2.13-android-x86_64

这位同学，你可能刚接触逆向还没有用真机的时候。模拟器所运行的arm环境全是基于x86上面的qume解释器完成的。大多数apk都是只打包arm版本，而模拟器的命令行却是x86的，这种情况下很多x86的指令在模拟的arm环境中是相冲突的。后续你会发现很多问题，这在真机上是完全没有的。谁是弱智这个问题很明显了。

第二：这是开源项目，你来用来了肯定是冲着某些提效利益（功能）来的。作者没有向任何一个人收取费用。这个东西用的好也好，坏也好，你都没有资格说赔偿。不要感觉这个都是世界围着你（弱智）转。
