### ISSUE TITLE
建议大佬加一个可以指定端口参数

### ISSUE THREAD

**Issue by irabbit666666** [CreditTone/hooker#40]
建议大佬加一个可以指定端口参数
有些app会检测端口

**Comment by CreditTone** [comment]
好建议……

**Comment by CreditTone** [comment]
加好了
https://github.com/CreditTone/hooker#5-%E6%8C%87%E5%AE%9Afridaserver%E7%AB%AF%E5%8F%A3%E7%9A%84%E6%89%8B%E6%9C%BA%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2

**Comment by irabbit666666** [comment]
感谢大佬,这下舒服了
