### ISSUE TITLE
想扩展AndroidUI，写自动化测试

### ISSUE THREAD

**Issue by wb-xiaoduan** [CreditTone/hooker#41]
打算再次扩展AndroidUI ，写一些自动化脚本，不知能否将radar.dex 开源。多谢

**Comment by CreditTone** [comment]
radar.dex项目是私有的要付会员费才可以进入哦！

**Comment by CreditTone** [comment]
你想加什么功能？

**Comment by CreditTone** [comment]
已开源radar，https://github.com/CreditTone/radar4hooker
