### ISSUE TITLE
咨询记录

### ISSUE THREAD

**Issue by CreditTone** [CreditTone/hooker#5]
好吧，我刚刚做安卓逆向，看你软件用起来挺方便的，我每次手动搞挺麻烦的，自己写一套没几个月写不下了，有机会在合作

---原始邮件---
发件人: "来自牛逼的爬虫工程师"<1273568669@qq.com>
发送时间: 2020年9月19日(周六) 中午12:43
收件人: "dorry"<xxxxxxxx@qq.com>;
主题: 回复：咨询爬虫软件

这个暂时不卖哈

发自我的iPhone

------------------ 原始邮件 ------------------
发件人: dorry <xxxxxxx@qq.com>
发送时间: 2020年9月19日 12:42
收件人: 来自牛逼的爬虫工程师 <1273568669@qq.com>
主题: 回复：咨询爬虫软件

HOOKER PRO

---原始邮件---
发件人: "来自牛逼的爬虫工程师"<1273568669@qq.com>
发送时间: 2020年9月19日(周六) 中午12:41
收件人: "dorry"<xxxxxxxx@qq.com>;
主题: 回复：咨询爬虫软件

需要买什么？

发自我的iPhone

------------------ 原始邮件 ------------------
发件人: dorry <xxxxxxx@qq.com>
发送时间: 2020年9月19日 12:41
收件人: 1273568669 <1273568669@qq.com>
主题: 回复：咨询爬虫软件

你好，咨询一下软件怎么卖

**Comment by dorry2015** [comment]
你好，那些pro功能我已经写完了

**Comment by CreditTone** [comment]
我都没说我pro有哪些功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dorry2015 <notifications@github.com&gt;
发送时间: 2020年10月27日 14:39
收件人: CreditTone/hooker <hooker@noreply.github.com&gt;
抄送: guozhong <1273568669@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CreditTone/hooker] 咨询记录 (#5)





 
你好，那些pro功能我已经写完了

**Comment by dorry2015** [comment]
看到你哔哩哔哩上发的视频的那些命令

**Comment by wen110** [comment]
> 我都没说我pro有哪些功能 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: dorry2015 <notifications@github.com&gt; 发送时间: 2020年10月27日 14:39 收件人: CreditTone/hooker <hooker@noreply.github.com&gt; 抄送: guozhong <1273568669@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[CreditTone/hooker] 咨询记录 (#5) 你好，那些pro功能我已经写完了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，怎么联系你呢，有什么联系方式吗
