### ISSUE TITLE
无法使用identifier进行attach

### ISSUE THREAD

**Issue by cokeBeer** [CreditTone/hooker#51]
这里输入com.ss.andriod.ugc.trill直接报错了。
如果输入TikTok可以attach，但是后面inject dex又会失败
![image](https://user-images.githubusercontent.com/70683161/150684569-8ad0fea9-234c-494b-bd06-c3421155ab03.png)

**Comment by cokeBeer** [comment]
使用adb连接手机以后执行ps指令，可以看到TikTok的进程名称后面多了一个:push
![image](https://user-images.githubusercontent.com/70683161/150685291-c72043c8-b39e-443e-a147-9517bec42334.png)

**Comment by zhaoyongping** [comment]
还是手撸吧，贪图自动化省事不行，各种报错和不兼容不适配。还是手动最靠谱
